name: Frontend CI/CD

on: 
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Application tests
    steps: 
      - name: Fetch code
        uses: actions/checkout@v4.1.1

      - name: Install node
        uses: actions/setup-node@v3
        with: 
          node-version: 18
        
      - name: Install dependencies
        run: npm install 
        working-directory: react-dine-frontend
      
      - name: Run tests
        run: npm run test:ci
        working-directory: react-dine-frontend